---
- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.11.0"
  name: clickhouse 
- src: git@github.com:kaakors/vector-role.git
  scm: git
  name: vector
- src: git@github.com:kaakors/nginx-role.git
  scm: git
  name: nginx
- src: git@github.com:kaakors/lighthouse-role.git
  scm: git
  name: lighthouse
